### ISSUE TITLE
The README should have a copy-paste:able command for installing dependencies on Ubuntu

### ISSUE THREAD

**Issue by simonlindholm** [Kattis/problemtools#105]
Right now you have to manually remove commas and parentheses with versions and prepend `sudo apt install`, unless there's some simple apt command I'm missing.

**Comment by godmar** [comment]
It's probably close to what I did in #114 for Ubuntu on Windows.

**Comment by simonlindholm** [comment]
I've had success with telling people to use the following:
```
sudo apt install libboost-regex-dev libc6 libgcc1 automake libgmp-dev libgmp10 libgmpxx4ldbl libstdc++6 python python-yaml python-plastex texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra texlive-lang-cyrillic tidy ghostscript
```

the differences to your linked command line being that mine includes: `libboost-regex-dev, libc6, libgcc1,  libgmp10, libgmpxx4ldbl, libstdc++6, python, python-yaml, python-plastex, ghostscript`
while yours includes: `virtualenv, libboost-all-dev, texlive-latex-base, texlive-fonts-extra, texlive-lang-greek, openjdk-8-jre-headless`

**Comment by godmar** [comment]
I included virtualenv so I could install your pip into a virtual environment rather than into personal space (or system wide); if you have root and are willing to install in your home directory you don't need it. I just like it personally.

If you don't install a version of Java (like openjdk-8-jre-headless) then VIVA will not work, and in fact fail with a weird error.  

The GMP packages are probably necessary on WSL as well and should be included, I think I had those from some previous software I installed.  

For the texlive stuff, I just tried a few things and then noted everything I'd installed.  Without the cyrillic package you get a weird error about ot2enc.def not defined.

And I think latex*recommend probably includes *base.  Having some redundant packages is probably not a killer.

**Comment by austrin** [comment]
I went with the list of packages used by the Docker images (which might have some redundancies but I think it is about as small as it can be).

**Comment by godmar** [comment]
This won't support viva, which needs a JRE.

Also, semi-related, I wasn't able to get the docker images to work, specifically couldn't get the bind mount to work.  Obviously, this is not a problemtools issue, but WSL is orders of magnitude more convenient than Docker for people who choose or have to run problemtools in Windows. (Just the fact that in order to install Docker, you have [to disable VirtualBox](https://medium.com/@peorth/using-docker-with-virtualbox-and-windows-10-b351e7a34adc) is annoying). Consider officially supporting it.

**Comment by austrin** [comment]
> This won't support viva, which needs a JRE.

This is true, but I don't really want to say that this is a dependency for problemtools because it is only a dependency for working with packages that have viva scripts, which is a small fraction of all packages.

What I *do* want to do however is to improve the error message that one gets when VIVA fails due to Java being missing so that it is clear to the user that the error they just got can be resolved by installing Java.

> Consider officially supporting it.

I was actually just looking at your #114, nice! It seems like something that should be added to the documentation.
