### ISSUE TITLE
problem2pdf includes all samples twice

### ISSUE THREAD

**Issue by lukipuki** [Kattis/problemtools#14]
In a problem with two sample files 1.in and 2.in, the PDF generated by `problem2pdf` contains 1.in, 2.in, 1.in and finally 2.in. All sample inputs are included twice.

**Comment by ghamerly** [comment]
I believe this duplication occurs because in template.py, all samples get included (which is correct):
https://github.com/Kattis/problemtools/blob/master/src/template.py#L99
but then in problemset.cls, all samples called 1.in ... 9.in are also included (which seems incorrect for this usage -- i.e. problem2pdf):
https://github.com/Kattis/problemtools/blob/master/templates/latex/problemset.cls#L162

It seems to me like the "right" thing to do is to either remove the automatic inclusion in problemset.cls (since it only works on a limited set of possible filenames), or at least to have an option to the class file that turns off automatic inclusion.

**Comment by godmar** [comment]
FWIW, the description available on the problem archive doesn't document the convention that test cases have to start with 1.in, 2.in etc. to be auto-included. I learned this only from examining problemset.cls.
