### ISSUE TITLE
Memory limit is not checked

### ISSUE THREAD

**Issue by meisterT** [Kattis/problemtools#38]
The `memory` limit is not applied to the submissions nor is `validation_memory` on validators.

Until this is fixed, I suggest to spit out a warning if a problem sets the memory limit explicitely in `problem.yaml`.

**Comment by austrin** [comment]
"fixed" in https://github.com/Kattis/problemtools/commit/c671fefb1409a80b94a157bad7f6fa2a4f4a2b48 and https://github.com/Kattis/problemtools/commit/b10cd30b863f9a442bf4cf47f5ed679fc9039f09.

TL;DR: for validators, memory limit is still not applied for build/run programs.  Because Java.

In particular, using rlimits to restrict memory makes the JVM very unhappy and causes it to crash on startup, so programs that might involve the JVM can not have a memory rlimit applied to it.  For submissions this is not a big issue from  since memory is limited by -Xmx instead, but for validators given by build/run scripts, there is no way for problemtools to know if those build/run scripts involve starting a JVM, so we can't apply a memory limit on them.  In a bright and shiny future problemtools may support using cgroups to limit memory, if that is enabled on the system (or who knows, maybe the JVM will be able to boot even with memory rlimited to 1 GB), but for now, I'd like to consider this resolved.
